blogger/blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.ArticleView.as_view(), name='article'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
]

blogger/blogger/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
	url(r'^blog/', include('blog.urls')),
    url(r'^admin/', admin.site.urls),
]

blogger/blog/models.py
from django.db import models

# Create your models here.
class Tag(models.Model):
	#article = models.ForeignKey(Article, on_delete=models.CASCADE)
	tag_text = models.CharField(max_length=50)
	def __str__(self):
		return self.tag_text

class Article(models.Model):
	title = models.CharField(max_length=200)
	body = models.TextField()
	pub_date = models.DateTimeField('date published')
	created_date = models.DateTimeField('date created', auto_now_add=True)
	last_edit_date = models.DateTimeField('date last edited', auto_now=True)
	tags = models.ManyToManyField(Tag)
	def __str__(self):
		return self.title

class Comment(models.Model):
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	poster = models.CharField(max_length=20)
	body = models.TextField()
	pub_date = models.DateTimeField('date posted', auto_now_add=True)
	def __str__(self):
		addition = ""
		if len(self.body) > 50:
			addition = "..."
		return self.body[:50] + addition

blogger/blog/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from .models import Article, Tag, Comment

class IndexView(generic.ListView):
	template_name = 'blog/index.html'
	context_object_name = 'latest_article_list'

	def get_queryset(self):
		"""Return the last five published Articles."""
		return Article.objects.order_by('-pub_date')[:5]

class ArticleView(generic.DetailView):
	model = Article
	template_name = 'blog/article.html'

# Use non-generic views next time around
class TagView(generic.DetailView):
	model = Tag
	template_name = 'blog/tag.html'
	#context_object_name = 'tag_list'

	"""def get_queryset(self):
		return Tag.objects.order_by('pub_date')"""

blogger/blog/templates/blog/article.html
{% extends "blog/base.html" %}

{% block title %}{{ article.title }} - Blogger{% endblock %}

{% block content %}
<div id="container">
	<div id="article">
		<h1>{{ article.title }}</h1>
		<div class="date">Posted on {{ article.pub_date.date }}</div>

		{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

		<p>{{ article.body }}</p>
		<div class="date">Last edited on {{ article.last_edit_date.date }}</div>
		{% if article.tags.all %}
			<div id="tag_list">
				<span>Tags: </span>
				{% for tag in article.tags.all %}
		    		<a href="{% url 'blog:tag' tag.id %}" class="tag" id="tag{{ forloop.counter }}">{{ tag.tag_text }}</a>
				{% endfor %}
			</div>
		{% endif %}
	</div>
	<hr>
	<div id="comments">
		<h2>Comments</h2>
		{% if article.comment_set.all %}
			<div id="comment_list">
				{% for comment in article.comment_set.all %}
					<div class="comment" id="comment{{ forloop.counter }}">
						<div class="comment_header">
							<div class="poster">{{ comment.poster }}</div>
							<div class="date">{{ comment.pub_date }}</div>
						</div>
						<div class="comment_body">{{ comment.body }}</div>
					</div>
				{% endfor %}
			</div>
		{% else %}
			<p>No comments to display</p>
		{% endif %}
	</div>
</div>
{% endblock %}

blogger/blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}" />
    <title>{% block title %}Blogger{% endblock %}</title>
</head>

<body>
	<div id="top_navbar">
		<a href="{% url 'blog:index' %}" class="nav_item">Home</a>
		<a href="" class="nav_item">Lorem</a>
		<a href="" class="nav_item">Ipsum</a>
	</div>
	<div id="content">
		{% block content %}{% endblock %}
	</div>
	</body>
</html>

blogger/blog/templates/blog/index.html
{% extends "blog/base.html" %}

{% block content %}
<div id="container">
	<h1>All Articles</h1>

	{% if latest_article_list %}
	    <ul id="articles">
	    {% for article in latest_article_list %}
	        <li><a href="{% url 'blog:article' article.id %}">{{ article.title }}</a></li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>No articles are available.</p>
	{% endif %}
</div>
{% endblock %}

blogger/blog/templates/blog/tag.html
{% extends "blog/base.html" %}

{% block title %}{{ tag.tag_text }} - Blogger{% endblock %}

{% block content %}
<div id="container">
	<h1>Articles with tag <i>{{ tag.tag_text }}</i></h1>

	{% if tag.article_set.all %}
	    <ul id="articles">
	    {% for article in tag.article_set.all %}
	        <li><a href="{% url 'blog:article' article.id %}">{{ article.title }}</a></li>
	    {% endfor %}
	    </ul>
	{% else %}
	    <p>No articles are available.</p>
	{% endif %}
</div>
{% endblock %}